const MOVES = {
  ROCK: 'rock',
  PAPER: 'paper',
  SCISSORS: 'scissors'
};

const MOVE_ORDER = [MOVES.ROCK, MOVES.PAPER, MOVES.SCISSORS];

const BEATS = {
  [MOVES.ROCK]: MOVES.SCISSORS,
  [MOVES.PAPER]: MOVES.ROCK,
  [MOVES.SCISSORS]: MOVES.PAPER
};

const PLAYER_STATUS = {
  WAITING: 'waiting',
  READY: 'ready',
  ELIMINATED: 'eliminated',
  WINNER: 'winner',
  INACTIVE: 'inactive'
};

const ROLES = {
  PLAYER: 'player',
  ADMIN: 'admin'
};

const ROUND_INTERVAL_MS = 30_000;
const PROCESS_STAGE_DURATION_MS = 3_000;
const COMPETITION_STAGE_DURATION_MS = 5_000;

const MAX_STAGE = 0;
const MIN_STAGE = -9;

const STAGE_COUNT = Math.abs(MIN_STAGE - MAX_STAGE) + 1;

module.exports = {
  MOVES,
  MOVE_ORDER,
  BEATS,
  PLAYER_STATUS,
  ROLES,
  ROUND_INTERVAL_MS,
  PROCESS_STAGE_DURATION_MS,
  COMPETITION_STAGE_DURATION_MS,
  MAX_STAGE,
  MIN_STAGE,
  STAGE_COUNT
};
